const data = [
  {
    id: 1,
    name: "Oak Chair",
    price: 49,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: [
      "../oakchair.jpg",
      "../pinechair.jpg",
      "../cedarchair.jpg",
      "../resinchair.jpg",
    ],
    rating: 4,
  },
  {
    id: 2,
    name: "Oak Bed",
    price: 99,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: ["../bed.png", "../bed.png", "../bed.png", "../bed.png"],
    rating: 5,
  },
  {
    id: 3,
    name: "Oak Table",
    price: 59,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: [
      "../oaktable.jpg",
      "../cedartable.jpg",
      "../resintable.jpg",
      "../resintable.jpg",
    ],
    rating: 3,
  },
  {
    id: 4,
    name: "Oak Lamp",
    price: 29,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: ["../lamp.png", "../lamp.png", "../lamp.png", "../lamp.png"],
    rating: 5,
  },
  {
    id: 5,
    name: "Pine Chair",
    price: 49,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: [
      "../pinechair.jpg",
      "../pinechair.jpg",
      "../pinechair.jpg",
      "../pinechair.jpg",
    ],
    rating: 4,
  },
  {
    id: 6,
    name: "Pine Bed",
    price: 99,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: ["../bed.png", "../bed.png", "../bed.png", "../bed.png"],
    rating: 5,
  },
  {
    id: 7,
    name: "Pine Table",
    price: 59,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: [
      "../resintable.jpg",
      "../resintable.jpg",
      "../resintable.jpg",
      "../resintable.jpg",
    ],
    rating: 3,
  },
  {
    id: 8,
    name: "Pine Lamp",
    price: 29,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: ["../lamp.png", "../lamp.png", "../lamp.png", "../lamp.png"],
    rating: 5,
  },
  {
    id: 9,
    name: "Cedar Chair",
    price: 49,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: [
      "../cedarchair.jpg",
      "../cedarchair.jpg",
      "../cedarchair.jpg",
      "../cedarchair.jpg",
    ],
    rating: 4,
  },
  {
    id: 10,
    name: "Cedar Bed",
    price: 99,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: ["../bed.png", "../bed.png", "../bed.png", "../bed.png"],
    rating: 5,
  },
  {
    id: 11,
    name: "Cedar Table",
    price: 59,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: [
      "../cedartable.jpg",
      "../cedartable.jpg",
      "../cedartable.jpg",
      "../cedartable.jpg",
    ],
    rating: 3,
  },
  {
    id: 12,
    name: "Cedar Lamp",
    price: 29,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: ["../lamp.png", "../lamp.png", "../lamp.png", "../lamp.png"],
    rating: 5,
  },
  {
    id: 13,
    name: "Resin Chair",
    price: 49,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: [
      "../resinchair.jpg",
      "../resinchair.jpg",
      "../resinchair.jpg",
      "../resinchair.jpg",
    ],
    rating: 4,
  },
  {
    id: 14,
    name: "Resin Bed",
    price: 99,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: ["../bed.png", "../bed.png", "../bed.png", "../bed.png"],
    rating: 5,
  },
  {
    id: 15,
    name: "Resin Table",
    price: 59,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: [
      "../resintable.jpg",
      "../resintable.jpg",
      "../resintable.jpg",
      "../resintable.jpg",
    ],
    rating: 3,
  },
  {
    id: 16,
    name: "Resin Lamp",
    price: 39,
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.",
    images: ["../lamp.png", "../lamp.png", "../lamp.png", "../lamp.png"],
    rating: 5,
  },
];

export default data;
